/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'totalInPaisa' : bigint,
  'customerName' : string,
  'status' : string,
  'deliveryAddress' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'deliveryCity' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'priceInPaisa' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'priceInPaisa' : bigint,
  'stock' : bigint,
}
export interface _SERVICE {
  'getAvailableCities' : ActorMethod<[], Array<string>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, Array<OrderItem>],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];